<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>false</PublishTrimmed>
    <AssemblyName>Pinna2HRTF.Windows</AssemblyName>
    <RootNamespace>Pinna2HRTF.Windows</RootNamespace>
    <Version>1.0.0</Version>
    <InformationalVersion>1.0.0b</InformationalVersion>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <ApplicationIcon>Resources\app_icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Resources\app_icon.ico" />
    <None Include="..\..\ProjectSettingHelp.json" Link="ProjectSettingHelp.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
    <PackageReference Include="HelixToolkit.WinUI.SharpDX" Version="3.1.2" />
  </ItemGroup>
</Project>
